parameters:
  jsonrpc_server.jms.handlers: []

services:
  jsonrpc_server.jms_adapter.normalizer:
    class: Bankiru\Api\JsonRpc\Adapters\JMS\JmsNormalizerAdapter
    arguments:
    - "@jms_serializer"
    - "@jms_serializer.serialization_context_factory"
    public: false
